### ISSUE TITLE
I have Internal server error

### ISSUE THREAD

**Issue by DragonfireHD** [BlockHorizons/PerWorldPlayer#1]
Internal Server Error by PlayerManager
On line 28 
I have problem to join my server please respone i need this Plugin bugfree 🙃

Error code:
03:39:34] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 110" (EXCEPTION) in "plugins/PerWorldPlayer_dev-4.phar/src/BlockHorizons/PerWorldPlayer/player/PlayerManager" at line 28

**Comment by Muqsit** [comment]
Please paste the complete crashdump.
