### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BlackAngels56** [BlockHorizons/PerWorldPlayer#10]
I was in a creative world and when I tp to a player in survival world the plugin crash ! I tried to restart /reload the server but the plugin don't work! And in console is no error! Sorry (◞‸◟ㆀ) for my English!

**Comment by BlackAngels56** [comment]
Me as player I keep inventory in any world but for other player it's reset in every time when they leave a world

**Comment by Muqsit** [comment]
Yep, handling /reloads is at the moment too complicated, prefer restarting the server instead. There are no plans on making PerWorldPlayer `/reload`-compliant because that command is scheduled for removal in a major PMMP version.
