### ISSUE TITLE
Unable To Manage Inventory At All

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/PerWorldPlayer#16]
as soon as i install the plugin and restart the server... the whole inventory gets stuck.... im unable to get items (even in creative) i have op and its the same issue with my other friends on the server... pls help

**Comment by Muqsit** [comment]
Did you use /stop or did you /reload?

**Comment by BlackKnight683** [comment]
i stopped the server... installed the plugin, then started the server


before installing and after deleting the plugin... i was able to move stuff in my inventory, before that it was completely blocked :c

**Comment by Muqsit** [comment]
Does this plugin display any errors in console? With the given steps, I cannot reproduce this issue.
