### ISSUE TITLE
[BUG] EnderChest removed after dying

### ISSUE THREAD

**Issue by UnEnanoMas** [BlockHorizons/PerWorldPlayer#18]
Hello Goodnight

I wanted to report a bug that occurs after a player dies.

If the player saves in ender's chest (1 stone block) and then dies, when he returns to open the chest, the inventory of the ender's chest has disappeared

I don't think it's a problem with another plugin (since I don't have any other plugin for enderchest or anything like that)

**Minecraft: 1.16.40**
**Pocketmine: 3.15.4**
**PHP: 7.3**
**Platform: Windows 10, Android 10**

**Comment by Endermanbugzjfc** [comment]
Do you have a plugin that modify spawn location? Try remove that.

**Comment by UnEnanoMas** [comment]
I use MSpawns

**Comment by Muqsit** [comment]
Ender chest inventories are per-world by default. You can set it to false in config to make ender chests global (as opposed to per-world).
https://github.com/BlockHorizons/PerWorldPlayer/blob/4bda06ce7dc42c31eecacc8bd4aa144787f261e6/resources/config.yml#L12
