### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by Jemand2021** [BlockHorizons/PerWorldPlayer#20]
Hello the plugin is very good in itself, but since 2 days it no longer works and when starting the server I get this error: https://hastebin.com/ekerivinil.http It would be nice if you could help me PS: Hot on Discord Katze_2 # 6705

**Comment by DragonfireHD** [comment]
Guten Tag

**Comment by DragonfireHD** [comment]
Ich kann dir helfen

**Comment by Jemand2021** [comment]
Okay what do I have to do to fix it

**Comment by DragonfireHD** [comment]
Damit ich helfen kann musst du mir deinen richtigen Discord sagen oder mich anschreiben 
Name 👇 nutze alle zeichen 


》《 𐱅𐰇𐰼𐰰 》DragonfireHD98#8415

**Comment by KadTheHunter** [comment]
The reason for this is PHP 7.4 deprecated using curly braces to get individual characters inside a string.
The fix is a pretty simple one in libaysyncsql.

**Comment by KadTheHunter** [comment]
Fixed in #21, hopefully someone can merge it.
