### ISSUE TITLE
Please Update the Plugin to API 4.0.0

### ISSUE THREAD

**Issue by DragonfireHD** [BlockHorizons/PerWorldPlayer#26]
Hi nice day ,

Can you Update the Plugin to the 4.0.0 Servers but i need that on my Pm4 Server is for me very important Plugin :)

**Comment by DPG896** [comment]
yes. we need this plugin for our productions

**Comment by Muqsit** [comment]
[Dev Build #28](https://poggit.pmmp.io/babs/1f53a) is marked for release and supports PM4 👍
