### ISSUE TITLE
PM4 upgrade consultation

### ISSUE THREAD

**Issue by Endermanbugzjfc** [BlockHorizons/PerWorldPlayer#27]
I'm trying to update this plugin to PM4. However, the NBT compression which PerWorldPlayer was using had been removed since PM4. I have been thought of two plans to work around this:
1. Abandon the NBT compression and implement a database migration logic. So inventories from older PerWorldPlayer can still be supported. But older PerWorldPlayer will not be able to read inventories in the future. (Basically BC break)
2. Use zlib / libdeflate compression as an alternative. This **might** not cause BC break. But NBT compression is deprecated and shall not be used anymore.

My conversation with Dylan: https://discord.com/channels/373199722573201408/373214753147060235/939531277483253790

**Comment by Endermanbugzjfc** [comment]
@Muqsit I know you and Dylan will probably hate my idea. But I am still asking because with my implementation, only `WorldDatabaseUtils->getSerializer()` needs a change and its usages don't.

I want to make a BigEndianNbtCompressiveSerializer class that extends BigEndianNbtSerializer and bring back the removed methods (`...Compressed()`).

**Comment by Muqsit** [comment]
> @Muqsit I know you and Dylan will probably hate my idea. But I am still asking because with my implementation, only `WorldDatabaseUtils->getSerializer()` needs a change and its usages don't.
> 
> I want to make a BigEndianNbtCompressiveSerializer class that extends BigEndianNbtSerializer and bring back the removed methods (`...Compressed()`).

I understand the value in extending `BigEndianNbtSerializer`, but to avoid breaking [COI principle](https://en.wikipedia.org/wiki/Composition_over_inheritance), introducing `private static readSerialized(string) : CompoundTag` and `writeSerialized(CompoundTag) : string` methods instead would work well.

**Comment by MrBlasyMSK** [comment]
@Endermanbugzjfc Will you make a pull req to be public or will you make it private for you?

**Comment by Endermanbugzjfc** [comment]
> @Endermanbugzjfc Will you make a pull req to be public or will you make it private for you?

It will mostly be public.

**Comment by Muqsit** [comment]
[Dev Build #18](https://poggit.pmmp.io/babs/1f53a) is marked for release and supports PM4 👍

**Comment by MrBlasyMSK** [comment]
check #28 @Muqsit

**Comment by MrBlasyMSK** [comment]
again #29 @Muqsit
