### ISSUE TITLE
files

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/PerWorldPlayer#3]
Hi author!
The Plugin is great，could I reproduce the files to mcbbs? I marked you as the author in the MCBBS，Users download the files in your original github or poggit .

**Comment by Endermanbugzjfc** [comment]
> Hi author!
> The Plugin is great，could I reproduce the files to mcbbs? I marked you as the author in the MCBBS，Users download the files in your original github or poggit .

This?
https://www.mcbbs.net/
