### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by YaNIND** [BlockHorizons/PerWorldPlayer#30]
When you go to another world and back again your inventory is clear

**Comment by Muqsit** [comment]
Seems to work fine, can you send a recording?

**Comment by DPG896** [comment]
uhm yep, i tried the dev 36 build. my gamemode and my inventory resets when i transferred to my survival spawn to hub (the core was gone)

**Comment by DPG896** [comment]
the bug [here](https://youtu.be/mL4vHBz6Q3c)

**Comment by MrBlasyMSK** [comment]
https://streamable.com/rtzyyo

It also happens in my server

Dev: 36
PHP 8.0.17
OS: linux
Pocketmine 4.2.5

**Comment by MrBlasyMSK** [comment]
> Thanks for reporting, should be fixed in [d26dc63](https://github.com/BlockHorizons/PerWorldPlayer/commit/d26dc630c9dee03bcee0268165fedff36a7f6d7a), [Dev #38 phar](https://poggit.pmmp.io/r/169477/PerWorldPlayer_dev-38.phar) Can you give it a try?

give me 20 min

**Comment by Muqsit** [comment]
👍

**Comment by DPG896** [comment]
thanks
