### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by reyyan987** [BlockHorizons/PerWorldPlayer#31]
"Undefined array key 4" (EXCEPTION) in "plugins/PerWorldPlayer.phar/src/BlockHorizons/PerWorldPlayer/player/PlayerManager" at line 34
I'm using latest

**Comment by Muqsit** [comment]
This isn't sufficient info to debug the cause of the problem, please send the complete crashdump / backtrace.

**Comment by reyyan987** [comment]
Ok

**Comment by reyyan987** [comment]
`2022-03-31 [04:01:33.448] [Server thread/CRITICAL]: ErrorException: "Undefined array key 4" (EXCEPTION) in "plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerWorldPlayer/player/PlayerManager" at line 34
--- Stack trace ---
  #0 plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerWorldPlayer/player/PlayerManager(34): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[21] Undefined array key 4, string[115] phar:///home/container/plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerW, integer 34)
  #1 plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerWorldPlayer/world/WorldInstance(88): BlockHorizons\PerWorldPlayer\player\PlayerManager->get(object ipad54\netherblocks\player\Player#99108)
  #2 plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerWorldPlayer/world/WorldInstance(65): BlockHorizons\PerWorldPlayer\world\WorldInstance->save(object ipad54\netherblocks\player\Player#99108, object BlockHorizons\PerWorldPlayer\world\data\PlayerWorldData#122826, integer 1)
  #3 plugins/PerWorldPlayer_dev-34.phar/src/BlockHorizons/PerWorldPlayer/world/WorldListener(65): BlockHorizons\PerWorldPlayer\world\WorldInstance->onPlayerExit(object ipad54\netherblocks\player\Player#99108, NULL , true)
  #4 pmsrc/src/event/RegisteredListener(75): BlockHorizons\PerWorldPlayer\world\WorldListener->onPlayerQuit(object pocketmine\event\player\PlayerQuitEvent#122821)
  #5 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#122821)
  #6 pmsrc/src/player/Player(2075): pocketmine\event\Event->call()
  #7 pmsrc/src/network/mcpe/NetworkSession(581): pocketmine\player\Player->onPostDisconnect(string[7] timeout, NULL )
  #8 pmsrc/src/network/mcpe/NetworkSession(514): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #9 pmsrc/src/network/mcpe/NetworkSession(583): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#122811, string[7] timeout)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(151): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(string[7] timeout)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(75): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(integer 0, string[7] timeout)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#99633)
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1648692092.5757)
  #16 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #18 pmsrc/src/PocketMine(327): pocketmine\server()
  #19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---`

**Comment by Muqsit** [comment]
I may have addressed this in 26e770ce57eece097e319a19533fc43790ea206d, can you check if [Dev #38](https://poggit.pmmp.io/r/169477/PerWorldPlayer_dev-38.phar) fixes the crash?

**Comment by reyyan987** [comment]
Ok
