### ISSUE TITLE
Netherite armor problem

### ISSUE THREAD

**Issue by MrBlasyMSK** [BlockHorizons/PerWorldPlayer#37]
https://github.com/ipad54/INether/issues/20

I have been testing it and it only happens with this plugin out of all the ones I have.

PHP: 8.0.17
OS: linux
Pocketmine 4.2.6
dev: 38

**Comment by Muqsit** [comment]
Netherite isn't something PocketMine currently supports and Dylan has been vocal about the technical overhead of introducing them at this time into Pocketmine. I think it's safe to say plugins that implement netherite would be going out of their way to do so.

**Comment by MrBlasyMSK** [comment]
I didn't quite understand your message.

Anyway, leaving aside that Dylan has not implemented the Netherite, poggit is to create certain things that Pocketmine does not add by default and are verified, so they meet the requirements and rules of Poggit.

Both "Netherite" and "INether" are viable and I would like you to just implement that it is possible to put the armor on item frames.

**Comment by Muqsit** [comment]
I don't think the issue is the fault of this plugin.

**Comment by MrBlasyMSK** [comment]
> I don't think the issue is the fault of this plugin.

I am one of those people who remove all the plugins and go testing 1 x 1 that is failing, if you think I get confused I invite you to send me a video with the plugin "INether" and "PerWorldPlayer" putting a part of the netherite armor in an item frame.
I will take it back and leave if it is true.

**Comment by Muqsit** [comment]
Ask the INether plugin developer to look into this issue.
