### ISSUE TITLE
I need help whit inventory

### ISSUE THREAD

**Issue by UnEnanoMas** [BlockHorizons/PerWorldPlayer#9]
When I put the initial world (which has a core) I add it to the list of worlds that I want saved, and I go to another world that is not added to the list and is not deleted.

What I can do?

**Comment by Muqsit** [comment]
> to the list of worlds that I want saved
Can you elaborate what you mean by this?

**Comment by UnEnanoMas** [comment]
I want objects to only stay in the world where people spawn (Lobby) and when they go to another world (Survival) they can have another different inventory

**Comment by Muqsit** [comment]
By default, PerWorldPlayer will behave that way. If you made changes to BundledWorlds, revert it

**Comment by UnEnanoMas** [comment]
![Captura](https://user-images.githubusercontent.com/63286108/83028212-6665a300-a031-11ea-9b02-ec301b852b4b.PNG)

?? And now?

**Comment by Muqsit** [comment]
Yeah, that should work.
